apiVersion: v1
kind: ServiceAccount
metadata:
  name: persistent-volume-binder
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: persistent-volume-binder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:persistent-volume-binder
subjects:
- kind: ServiceAccount
  name: persistent-volume-binder
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pv-controller-manager
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      name: pv-controller-manager
      labels:
        app: pv-controller-manager
    spec:
      tolerations:
      - key: beta.kubernetes.io/arch
        value: arm
        effect: NoSchedule
      - key: beta.kubernetes.io/arch
        value: arm64
        effect: NoSchedule
      serviceAccountName: persistent-volume-binder
      containers:
      - name: pv-controller-manager
        image: luxas/storage-controller-manager:v1.6.0-beta.4
        command:
        - kube-controller-manager
        - --leader-elect=false
        - --controllers=persistentvolume-binder
        livenessProbe:
          failureThreshold: 8
          httpGet:
            path: /healthz
            port: 10252
          initialDelaySeconds: 15
          timeoutSeconds: 15
