kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2alpha1
metadata:
  name: my-hpa
spec:
  scaleTargetRef:
    kind: Deployment
    name: my-nginx
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      target:
        kind: Service
        name: my-nginx
      metricName: connections-per-seconds
      targetValue: 1000m
