kind: Namespace
apiVersion: v1
metadata:
  name: test-ns
---
apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Instance
metadata:
  name: ups-instance
  namespace: test-ns
spec:
  serviceClassName: user-provided-service
  planName: default
---
apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Binding
metadata:
  name: ups-binding
  namespace: test-ns
spec:
  instanceRef:
    name: ups-instance
  secretName: my-secret
